services:
    nginx:
        image: docker.io/nginx:stable-alpine
        env_file:
            - .env
        command: /bin/sh /entry.sh
        networks:
            - initfs_out
        ports:
            - ${NGINX_PORT}:80
        volumes:
            - ./${CONFIG_WEB}:/etc/nginx/templates
            - ./${BIN_NGINX_ENTRY}:/entry.sh
    redis:
        image: docker.io/redis:alpine
        restart: always
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']
            interval: 6s
            timeout: 6s
            retries: 10
        ports:
            - 6384:6379
        networks:
            - initfs_in
    mongo:
        env_file:
            - .env
        image: mongodb/mongodb-community-server:latest
        restart: always
        healthcheck:
            test:
                [
                    'CMD',
                    'mongosh',
                    '--eval',
                    '''db.runCommand("ping").ok''',
                    'localhost:27017/test',
                    '--quiet',
                ]
            interval: 6s
            timeout: 6s
            retries: 10
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=password2202
            - MONGO_USER_NAME=initfs
            - MONGO_USER_PASSWORD=password2
            - MONGO_DATABASE=initfs
        ports:
            - 27018:27017
        volumes:
            - ./${BIN_INIT_MONGO}:/docker-entrypoint-initdb.d/init_mongo_db.sh:ro
        networks:
            - initfs_in
    app:
        env_file:
            - .env
            - packages/web/.env
        build:
            context: .
            dockerfile: ./Dockerfile
            args:
                USERNAME: runner
                USER_UID: 1002
                USER_GID: 1002
                STAGE: 'false'
                BIN_DEPLOY: ${BIN_DEPLOY}
                DOCKER_ENV_DIR: ${DOCKER_ENV_DIR}
                BIN_DEPLOY_REQ_SERVER: ${BIN_DEPLOY_REQ_SERVER}
                NODE_VER: ${NODE_VER}
                BUN_VER: ${BUN_VER}
                PM2_WORKER: ${PM2_WORKER}
        networks:
            - initfs_out
            - initfs_in
        expose:
            - ${NODE_PORT}
        depends_on:
            redis:
                condition: service_healthy
            mongo:
                condition: service_healthy
networks:
    initfs_in:
        name: initfs_in
        driver: bridge
    initfs_out:
        name: initfs_out
        driver: bridge
