export default {
    entry: [
        'nuxt.config.{js,mjs,ts}',
        'src/app.config.ts',
        'src/app.vue',
        'src/error.vue',
        'src/pages/**/*.vue',
        'src/components/**/*.vue',
        'src/layouts/**.vue',
        'src/plugins/**/*.ts',
        'src/middleware/**/*.ts',
        'src/server/api/**/*.ts',
        'src/server/routes/**/*.ts',
        'src/server/middleware/**/*.ts',
        'src/server/plugins/**/*.ts',
        'modules/**/*.ts',
        'vitest.config.ts',
        'eslint.config.mjs',
    ],
    project: ['**/*.{js,cjs,mjs,jsx,ts,cts,mts,tsx,mdx,md,vue}'],
    ignore: ['.nuxt/**', '.data/**', 'app.config.ts'],
    ignoreBinaries: ['knip', 'eslint', 'nuxt', 'vitest'],
    ignoreDependencies: [
        '@nuxt/.*',
        '@nuxtjs/.*',
        'nuxt-*',
        'happy-dom',
        '@vue/*',
        '@pinia/nuxt',
        '@unhead/vue',
    ],
    compilers: {
        css: (text: string) => [...text.matchAll(/(?<=@)import[^;]+/g)].join('\n'),
        yaml: (text: string) => [...text.matchAll(/(?<=@)import[^;]+/g)].join('\n'),
    },
};
