memory:
    host: 'redis'
    port: 6379
storage:
    host: 'mongo'
    user: 'initfs'
    password: 'password2'
    port: 27017
model:
    cacheDb: 6
    statusDb: 7
    dataDb: 'initfs'
    cors: []
