cache:
    host: 'redis'
    port: 6379
storage:
    host: 'mongo'
    user: 'user'
    password: 'passwordUser'
    port: 3808
model:
    logger:
        name: 'LogName'
        level: 'notice'
        cacheDb: 6
        key: 'log'
    status:
        cacheDb: 7
        key: 'status'
    data:
        storageDb: 'name'
    cors: []
