name: main

on:
    pull_request:
    push:
        branches: [main]

jobs:
    lin_lint:
        strategy:
            fail-fast: false
        runs-on: ubuntu-latest
        steps:
            - name: Set up Node 22
              uses: actions/setup-node@v4
              with:
                  node-version: '22'
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Install dependencies
              run: |
                  sudo mkdir -p $HOME
                  sudo mkdir -p $HOME/.local/bin
                  sudo chown runner -R $HOME
                  sudo apt install -y curl git-lfs
            - name: lint and test
              run: |
                  make dev
                  export GITHUB_WORKER='true'
                  make runChecks
